# Generated by Django 2.2.6 on 2019-10-23 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bible', '0002_remove_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
